# Generated by Django 3.0.5 on 2020-04-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackAPI', '0002_auto_20200428_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
