# Generated by Django 3.0.5 on 2020-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackAPI', '0003_auto_20200429_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_view_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
